# Generated by Django 6.1.1 on 2026-09-12 12:58

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineageEntry',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mai', 'Maithili')], default='en', max_length=5)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_relation_to_candidate', models.CharField(max_length=100)),
                ('guardian_village', models.CharField(blank=True, max_length=150)),
                ('guardian_district', models.CharField(blank=True, max_length=150)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('candidate_full_name', models.CharField(max_length=150)),
                ('candidate_gender', models.CharField(choices=[('Bride', 'Bride'), ('Groom', 'Groom')], max_length=5)),
                ('candidate_dob', models.DateField()),
                ('candidate_education', models.CharField(blank=True, max_length=200)),
                ('candidate_occupation', models.CharField(blank=True, max_length=200)),
                ('candidate_current_city', models.CharField(blank=True, max_length=150)),
                ('gotra', models.CharField(blank=True, max_length=150)),
                ('mool_gram', models.CharField(blank=True, max_length=150)),
                ('paternal_line', django_mongodb_backend.fields.EmbeddedModelArrayField(blank=True, default=list, embedded_model='registrations.lineageentry')),
                ('maternal_line', django_mongodb_backend.fields.EmbeddedModelArrayField(blank=True, default=list, embedded_model='registrations.lineageentry')),
                ('consent_choice', models.CharField(blank=True, choices=[('agree', 'Agree'), ('not-yet', 'Not yet')], max_length=10)),
                ('consent_own_words', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchProposal',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_by_panjikar', models.CharField(max_length=150)),
                ('proposed_on', models.DateField(auto_now_add=True)),
                ('shared_details', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list)),
                ('your_response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('other_response', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('contact_guardian_name', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_proposals', to='registrations.registration')),
            ],
            options={
                'ordering': ['-proposed_on'],
            },
        ),
        migrations.CreateModel(
            name='ConcernReport',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_reference_text', models.CharField(blank=True, help_text="Raw reference as typed by the user, kept even if it doesn't match a real Registration.", max_length=20)),
                ('topic', models.CharField(blank=True, choices=[('detail_feels_wrong', 'A detail feels wrong'), ('unwanted_contact', 'Unwanted contact'), ('unsure_about_match', 'Unsure about a match'), ('something_else', 'Something else')], max_length=30)),
                ('description', models.TextField()),
                ('contact_back', models.CharField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concern_reports', to='registrations.registration')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
