# Generated by Django 6.1.1 on 2026-09-14 07:34

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_matchproposal_paired_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAttemptLog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('matched', 'Matched'), ('no_eligible_candidate', 'No eligible candidate')], max_length=30)),
                ('candidates_considered', models.JSONField(blank=True, default=list)),
                ('sapinda_rules_version', models.CharField(blank=True, max_length=50)),
                ('matched_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registrations.registration')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_attempts', to='registrations.registration')),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
    ]
