# Generated by Django 6.1.1 on 2026-09-21 10:42

import uuid

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


def drop_match_collection(apps, schema_editor):
    """Drop the stale Match collection left over from prior failed
    migration attempts. Uses a fresh PyMongo client to bypass any
    Django connection caching that may hide the collection.
    """
    from pymongo import MongoClient
    client = MongoClient("mongodb://localhost:27017/")
    for db_name in client.list_database_names():
        if db_name in ("local", "config"):
            continue
        db = client[db_name]
        if "registrations_match" in db.list_collection_names():
            db.command("drop", "registrations_match")
    client.close()


def backfill_registration_tokens(apps, schema_editor):
    Registration = apps.get_model("registrations", "Registration")
    for registration in Registration.objects.filter(token__in=["", None]):
        registration.token = str(uuid.uuid4())
        registration.save(update_fields=["token"])


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registration_owner'),
    ]

    operations = [
        migrations.RunPython(drop_match_collection, migrations.RunPython.noop),
        migrations.AddField(
            model_name='registration',
            name='token',
            field=models.CharField(editable=False, max_length=36, null=True),
        ),
        migrations.RunPython(backfill_registration_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='registration',
            name='token',
            field=models.CharField(db_index=True, editable=False, max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('matched_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('viewed', 'Viewed')], default='pending', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_candidate', to='registrations.registration')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='registrations.registration')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'indexes': [models.Index(fields=['status'], name='registratio_status_69e494_idx'), models.Index(fields=['matched_on'], name='registratio_matched_609c22_idx')],
            },
        ),
    ]