# Generated by Django 6.1.1 on 2026-09-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_registration_token_match'),
    ]

    operations = [
        # No-op: migration 0005 previously created explicit indexes on
        # Match.registration and Match.candidate that duplicated the
        # auto-created ForeignKey indexes. 0005 now creates only the
        # status/matched_on indexes matching the model, so the duplicate
        # explicit indexes no longer exist and there is nothing to remove.
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
