from django.contrib import admin

from .models import ConcernReport, MatchAttemptLog, MatchProposal, Registration


@admin.register(Registration)
class RegistrationAdmin(admin.ModelAdmin):
    list_display = [
        "reference",
        "candidate_full_name",
        "candidate_gender",
        "verification_status",
        "withdrawn",
        "created_at",
    ]
    list_filter = ["verification_status", "candidate_gender", "withdrawn"]
    search_fields = [
        "reference", "candidate_full_name", "guardian_name",
        "guardian_phone", "guardian_email",
    ]
    readonly_fields = ["reference", "created_at", "updated_at", "owner"]

    fieldsets = (
        ("Registration", {
            "fields": (
                "reference", "owner", "language", "verification_status",
                "withdrawn", "withdrawn_at", "created_at", "updated_at",
            )
        }),
        ("Guardian", {
            "fields": (
                "guardian_name", "guardian_relation_to_candidate",
                "guardian_village", "guardian_district",
                "guardian_phone", "guardian_email",
            )
        }),
        ("Candidate", {
            "fields": (
                "candidate_full_name", "candidate_gender", "candidate_dob",
                "candidate_education", "candidate_occupation", "candidate_current_city",
            )
        }),
        ("Partner preferences", {
            "fields": (
                "preferred_age_min", "preferred_age_max",
                "preferred_location", "preferred_education",
            )
        }),
        ("Lineage", {
            "fields": ("gotra", "mool_gram", "paternal_line", "maternal_line"),
            "description": (
                "If this section fails to render or throws an error, remove "
                "paternal_line/maternal_line from this fieldset — MongoDB's "
                "EmbeddedModelArrayField doesn't always have full Django admin "
                "widget support. A dedicated lineage-review screen (reusing "
                "your existing /panjikar/lineage page, once properly secured) "
                "is a better long-term home for this than the admin form."
            ),
        }),
        ("Consent", {
            "fields": ("consent_choice", "consent_own_words")
        }),
    )

    actions = ["mark_verified"]

    @admin.action(description="Mark selected registrations as verified")
    def mark_verified(self, request, queryset):
        # IMPORTANT: loop + .save() individually — do NOT use queryset.update().
        # update() bypasses .save() entirely, which means the pre_save/post_save
        # signals in signals.py never fire, and the automated matching engine
        # would silently never run for these registrations.
        count = 0
        for reg in queryset:
            if reg.verification_status != Registration.VerificationStatus.VERIFIED:
                reg.verification_status = Registration.VerificationStatus.VERIFIED
                reg.save()
                count += 1
        self.message_user(
            request,
            f"Verified {count} registration(s). Automated matching has been triggered for each.",
        )


@admin.register(MatchProposal)
class MatchProposalAdmin(admin.ModelAdmin):
    list_display = ["id", "registration", "your_response", "other_response", "state", "proposed_on"]
    list_filter = ["your_response", "other_response"]
    readonly_fields = [f.name for f in MatchProposal._meta.fields] + ["state"]
    # Fully read-only — these rows are system-generated by the matching
    # engine and should never be hand-edited from the admin.


@admin.register(ConcernReport)
class ConcernReportAdmin(admin.ModelAdmin):
    list_display = ["id", "registration", "topic", "resolved", "submitted_at"]
    list_filter = ["topic", "resolved"]
    readonly_fields = [
        "registration", "registration_reference_text",
        "topic", "description", "contact_back", "submitted_at",
    ]
    # "resolved" stays editable — this is the one place you'd mark a
    # reported concern as looked into.


@admin.register(MatchAttemptLog)
class MatchAttemptLogAdmin(admin.ModelAdmin):
    list_display = ["registration", "outcome", "matched_registration", "ran_at"]
    list_filter = ["outcome"]
    readonly_fields = [
        "registration", "ran_at", "outcome", "matched_registration",
        "candidates_considered", "sapinda_rules_version",
    ]